version: "3.4"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: groot
      POSTGRES_USER: groot
      POSTGRES_DB: groot
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  groot_api:
    container_name: groot_api
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - rust:latest
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_started
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 3030
      DATABASE_URL: postgres://groot:groot@postgres:5432/groot
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'
    ports:
      - 3030:3030
