on:
  push:
    branches:
      - '*'
  pull_request:
  schedule:
    - cron:  '13 5 * * *'

name: Continuous Integration

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Get requirements.yml
        run: curl https://raw.githubusercontent.com/pulp/pulp_installer/master/requirements.yml -o requirements.yml

      - name: Run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- sync --requirement requirements.yml

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Get requirements.yml
        run: curl https://raw.githubusercontent.com/pulp/pulp_installer/master/requirements.yml -o requirements.yml

      - name: Run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- sync --requirement requirements.yml

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Get requirements.yml
        run: curl https://raw.githubusercontent.com/pulp/pulp_installer/master/requirements.yml -o requirements.yml

      - name: Run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- sync --requirement requirements.yml
