name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: groot
            asset_name: groot-linux-amd64
          - os: macos-latest
            artifact_name: groot
            asset_name: groot-macos-amd64

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

  image:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: actions/checkout@v3
      - name: Quay login
        env:
          QUAY_BOT_PASSWORD: ${{ secrets.QUAY_BOT_PASSWORD }}
          QUAY_BOT_USERNAME: ${{ secrets.QUAY_BOT_USERNAME }}
        run: echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io
      - name: Push image to quay
        run: |
          sed -e '1 s/\(^FROM\)/FROM --platform=\$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=\$\{BUILDPLATFORM\}/' Dockerfile > Dockerfile.cross
          docker buildx create --name project-v3-builder
          docker buildx use project-v3-builder
          PLATFORMS=linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
          docker buildx build --push --platform=${PLATFORMS} --tag quay.io/fabricio_aguiar/groot:stable -f Dockerfile.cross .
          docker buildx build --push --platform=${PLATFORMS} --tag quay.io/fabricio_aguiar/groot:${GITHUB_REF##*/} -f Dockerfile.cross .
          docker buildx rm project-v3-builder
          rm Dockerfile.cross